name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0
      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: repo/image
          tag: latest
          registry: dockerhub.io
          dockerfile: Dockerfile
